<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SubscriptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('subscriptions')->delete();
        
        \DB::table('subscriptions')->insert(array (
            0 => 
            array (
                'id' => 14,
                'user_id' => 3,
                'category_id' => 5,
                'name' => 'Xbox Game Pass Console',
                'description' => NULL,
                'amount' => '109000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 1,
                'start_date' => '2026-07-28',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 1,
                'invite_code' => 'GRP-4TAOEA',
                'logo' => 'https://icon.horse/icon/xbox.com',
                'created_at' => '2026-07-28 02:22:07',
                'updated_at' => '2026-07-31 05:39:08',
            ),
            1 => 
            array (
                'id' => 15,
                'user_id' => 3,
                'category_id' => 1,
                'name' => 'Netflix Mobile',
                'description' => NULL,
                'amount' => '54000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 29,
                'start_date' => '2026-07-28',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 1,
                'status' => 'active',
                'is_public' => 1,
                'invite_code' => 'GRP-AY0LGC',
                'logo' => 'https://icon.horse/icon/netflix.com',
                'created_at' => '2026-07-28 03:37:30',
                'updated_at' => '2026-08-16 10:27:00',
            ),
            2 => 
            array (
                'id' => 17,
                'user_id' => 3,
                'category_id' => 6,
                'name' => 'Google Workspace Starter',
                'description' => NULL,
                'amount' => '96000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 1,
                'start_date' => '2026-07-30',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-WC4TBW',
                'logo' => 'https://icon.horse/icon/workspace.google.com',
                'created_at' => '2026-07-30 04:19:51',
                'updated_at' => '2026-07-30 04:19:51',
            ),
            3 => 
            array (
                'id' => 18,
                'user_id' => 3,
                'category_id' => 1,
                'name' => 'Disney+ Hotstar Basic',
                'description' => NULL,
                'amount' => '65000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 1,
                'start_date' => '2026-07-31',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-CR0CUI',
                'logo' => 'https://icon.horse/icon/hotstar.com',
                'created_at' => '2026-07-31 05:01:42',
                'updated_at' => '2026-07-31 05:01:42',
            ),
            4 => 
            array (
                'id' => 19,
                'user_id' => 3,
                'category_id' => 1,
                'name' => 'Disney+ Hotstar',
                'description' => NULL,
                'amount' => '119000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 1,
                'start_date' => '2026-07-31',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-J0NDAR',
                'logo' => 'https://img.icons8.com/?size=512&id=o7YMV0TFYOgR&format=png',
                'created_at' => '2026-07-31 05:06:47',
                'updated_at' => '2026-07-31 05:06:47',
            ),
            5 => 
            array (
                'id' => 20,
                'user_id' => 3,
                'category_id' => 7,
                'name' => 'BPJS Kesehatan Kelas 1',
                'description' => NULL,
                'amount' => '150000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 1,
                'start_date' => '2026-08-01',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-RU66RD',
                'logo' => 'https://icon.horse/icon/bpjs-kesehatan.go.id',
                'created_at' => '2026-08-01 14:08:35',
                'updated_at' => '2026-08-01 14:08:35',
            ),
            6 => 
            array (
                'id' => 21,
                'user_id' => 3,
                'category_id' => 6,
                'name' => 'Gemini Ultra',
                'description' => NULL,
                'amount' => '1579000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 10,
                'start_date' => '2026-08-02',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-L406AH',
                'logo' => 'https://icon.horse/icon/gemini.google.com',
                'created_at' => '2026-08-02 06:07:05',
                'updated_at' => '2026-08-02 06:07:05',
            ),
            7 => 
            array (
                'id' => 22,
                'user_id' => 3,
                'category_id' => 6,
                'name' => 'Claude',
                'description' => NULL,
                'amount' => '320000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 15,
                'start_date' => '2026-08-15',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 6,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-XB2LKV',
                'logo' => 'https://icon.horse/icon/claude.ai',
                'created_at' => '2026-08-15 03:28:11',
                'updated_at' => '2026-08-15 03:28:11',
            ),
            8 => 
            array (
                'id' => 23,
                'user_id' => 3,
                'category_id' => 1,
                'name' => 'Vision+ Premium Sports',
                'description' => NULL,
                'amount' => '40000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 16,
                'start_date' => '2026-08-16',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 1,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-DS4NPB',
                'logo' => 'https://www.google.com/s2/favicons?domain=visionplus.id&sz=128',
                'created_at' => '2026-08-15 04:02:38',
                'updated_at' => '2026-08-15 04:02:38',
            ),
            9 => 
            array (
                'id' => 24,
                'user_id' => 3,
                'category_id' => 1,
                'name' => 'iQIYI VIP Standard',
                'description' => NULL,
                'amount' => '39000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 19,
                'start_date' => '2026-08-19',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 1,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-STBKV0',
                'logo' => 'https://icon.horse/icon/iq.com',
                'created_at' => '2026-08-16 09:45:44',
                'updated_at' => '2026-08-16 09:45:44',
            ),
            10 => 
            array (
                'id' => 25,
                'user_id' => 6,
                'category_id' => 1,
                'name' => 'YouTube Music Student',
                'description' => NULL,
                'amount' => '24990.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 16,
                'start_date' => '2026-08-16',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-MLFP5J',
                'logo' => 'https://icon.horse/icon/music.youtube.com',
                'created_at' => '2026-08-16 10:50:15',
                'updated_at' => '2026-08-16 10:50:15',
            ),
            11 => 
            array (
                'id' => 28,
                'user_id' => 2,
                'category_id' => 1,
                'name' => 'WeTV',
                'description' => NULL,
                'amount' => '53000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 16,
                'start_date' => '2026-08-18',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 2,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-MOSQ2S',
                'logo' => 'https://icon.horse/icon/wetv.vip',
                'created_at' => '2026-08-18 11:26:04',
                'updated_at' => '2026-08-18 11:26:04',
            ),
            12 => 
            array (
                'id' => 30,
                'user_id' => 2,
                'category_id' => 5,
                'name' => 'Xbox Game Pass Ultimate',
                'description' => NULL,
                'amount' => '169000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 11,
                'start_date' => '2026-08-18',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 2,
                'status' => 'active',
                'is_public' => 1,
                'invite_code' => 'GRP-MN2OOV',
                'logo' => 'https://icon.horse/icon/xbox.com',
                'created_at' => '2026-08-18 11:27:23',
                'updated_at' => '2026-08-18 11:28:12',
            ),
            13 => 
            array (
                'id' => 31,
                'user_id' => 2,
                'category_id' => 6,
                'name' => 'Claude',
                'description' => NULL,
                'amount' => '320000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 25,
                'start_date' => '2026-08-18',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-EIUTJW',
                'logo' => 'https://icon.horse/icon/claude.ai',
                'created_at' => '2026-08-18 11:37:35',
                'updated_at' => '2026-08-18 11:37:35',
            ),
            14 => 
            array (
                'id' => 32,
                'user_id' => 2,
                'category_id' => 6,
                'name' => 'Gemini Plus',
                'description' => NULL,
                'amount' => '75000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 23,
                'start_date' => '2026-08-18',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-NHNWDO',
                'logo' => 'https://icon.horse/icon/gemini.google.com',
                'created_at' => '2026-08-18 11:38:18',
                'updated_at' => '2026-08-18 11:38:18',
            ),
            15 => 
            array (
                'id' => 33,
                'user_id' => 2,
                'category_id' => 1,
                'name' => 'Netflix',
                'description' => NULL,
                'amount' => '120000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 25,
                'start_date' => '2026-08-18',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-8NTN0I',
                'logo' => 'https://icon.horse/icon/netflix.com',
                'created_at' => '2026-08-18 11:39:58',
                'updated_at' => '2026-08-18 11:39:58',
            ),
            16 => 
            array (
                'id' => 34,
                'user_id' => 2,
                'category_id' => 1,
                'name' => 'Apple TV+',
                'description' => NULL,
                'amount' => '99000.00',
                'currency' => 'IDR',
                'billing_cycle' => 'monthly',
                'payment_date' => 28,
                'start_date' => '2026-08-18',
                'end_date' => NULL,
                'auto_renew' => 1,
                'reminder_days' => 3,
                'status' => 'active',
                'is_public' => 0,
                'invite_code' => 'GRP-BPPIBD',
                'logo' => 'https://icon.horse/icon/tv.apple.com',
                'created_at' => '2026-08-18 11:41:44',
                'updated_at' => '2026-08-18 11:41:44',
            ),
        ));
        
        
    }
}